[package]
name = "sourceview"
version = "0.1.3"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the GtkSourceView 3 library"
repository = "https://github.com/gtk-rs/sourceview"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/sourceview/"

keywords = ["sourceview", "gtk", "gtk-rs", "gnome", "GUI"]

[lib]
name = "sourceview"

[features]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gio/embed-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gio/purge-lgpl-docs"]
v2_0  = ["gtk-source-sys/v2_0"]
v2_2  = ["v2_0", "gtk-source-sys/v2_2"]
v2_4  = ["v2_2", "gtk-source-sys/v2_4"]
v2_8  = ["v2_4", "gtk-source-sys/v2_8"]
v2_10 = ["v2_8", "gtk-source-sys/v2_10"]
v2_12 = ["v2_10", "gtk-source-sys/v2_12"]
v3_0  = ["v2_12", "gtk-source-sys/v3_0"]
v3_10 = ["v3_0", "gtk-source-sys/v3_10"]
v3_12 = ["v3_10", "gtk-source-sys/v3_12"]
v3_16 = ["v3_12", "gtk-source-sys/v3_16"]
v3_18 = ["v3_16", "gtk-source-sys/v3_18"]
v3_20 = ["v3_18", "gtk-source-sys/v3_20"]
default = ["v2_0"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.1"
optional = true

[dependencies]
libc = "0.2"
bitflags = "0.5"
gtk-source-sys = "^0.3.4"
glib-sys = "^0.3.4"
gobject-sys = "^0.3.4"
gtk-sys = "^0.3.4"
gdk-sys = "^0.3.4"
gdk-pixbuf-sys = "^0.3.4"
glib = "^0.1.3"
pango = "^0.1.3"
gtk = "^0.1.3"
gdk = "^0.5.3"
cairo-rs = "^0.1.3"
gdk-pixbuf = "^0.1.3"
gio = "^0.1.3"
