[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
gobject-sys = "0.4.0"
glib-sys = "0.4.0"
gio-sys = "0.4.0"
cairo-sys-rs = "0.4.0"
gtk-sys = "0.4.0"
gdk-pixbuf-sys = "0.4.0"
libc = "0.2"
gdk-sys = "0.4.0"
bitflags = "0.9"

[features]
v3_20 = ["v3_18"]
v3_4 = []
v3_18 = ["v3_16"]
v3_12 = ["v3_10"]
v3_8 = ["v3_4"]
v3_16 = ["v3_14"]
v3_10 = ["v3_8"]
v3_14 = ["v3_12"]

[lib]
name = "gtk_source_sys"

[package]
name = "gtk-source-sys"
license = "MIT"
homepage = "http://gtk-rs.org/"
links = "gtk_source"
authors = ["The Gtk-rs Project Developers"]
description = "FFI bindings to libgtksourceview-3"
version = "0.4.0"
keywords = ["gtk", "ffi", "gtk-rs", "gnome", "sourceview"]
repository = "https://github.com/gtk-rs/sourceview"
build = "build.rs"
