[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
libc = "0.2"
bitflags = "0.9"

[dependencies.cairo-sys-rs]
version = "0.4.0"
git = "https://github.com/gtk-rs/cairo"

[dependencies.gdk-pixbuf-sys]
version = "0.4.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gdk-sys]
version = "0.4.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gio-sys]
version = "0.4.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.glib-sys]
version = "0.4.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
version = "0.4.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gtk-sys]
version = "0.4.0"
git = "https://github.com/gtk-rs/sys"

[features]
v3_20 = ["v3_18"]
v3_4 = []
v3_18 = ["v3_16"]
v3_12 = ["v3_10"]
v3_8 = ["v3_4"]
v3_16 = ["v3_14"]
v3_10 = ["v3_8"]
v3_14 = ["v3_12"]

[lib]
name = "gtk_source_sys"

[package]
name = "gtk-source-sys"
links = "gtk_source"
version = "0.4.0"
build = "build.rs"