[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.8"
libc = "0.2"

[dependencies.gdk-pixbuf-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.gdk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo"
version = "0.3.4"

[features]
v2_0 = []
v2_10 = ["v2_8"]
v2_12 = ["v2_10"]
v2_2 = ["v2_0"]
v2_4 = ["v2_2"]
v2_8 = ["v2_4"]
v3_0 = ["v2_12"]
v3_10 = ["v3_8"]
v3_12 = ["v3_10"]
v3_14 = ["v3_12"]
v3_16 = ["v3_14"]
v3_18 = ["v3_16"]
v3_20 = ["v3_18"]
v3_4 = ["v3_0"]
v3_8 = ["v3_4"]

[lib]
name = "gtk_source_sys"

[package]
build = "build.rs"
links = "gtk_source"
name = "gtk-source-sys"
version = "0.1.3"
